---

# This script checks the current status of application
# If it is already installed, we should compare setting and update them if necessary
# If it is not installed, we should provide correct options for installation

- name: "Check whether {{ app_name }} RPM is installed"
  command: "rpm -qa {{ rpm_name }}"
  args:
    warn: no
  register: rpm_is_installed

- name: "Get actual installation prefix for {{ app_name }}"
  when: rpm_is_installed.stdout != ''
  shell: "rpm -ql {{ rpm_name }} | grep -v '/etc/talend/{{ rpm_folder }}' | head -n 1"
  args:
    warn: no
  register: rpm_install_path

- name: "Show error if {{ app_name }} is already installed with a different prefix"
  fail:
    msg: "Error: {{ app_name }} is already installed with a different prefix ( {{ rpm_install_path.stdout }} )"
  when: rpm_is_installed.stdout != '' and rpm_install_path.stdout != install_prefix

- name: Check that installation is valid
  stat:
    path: "{{ install_prefix }}/{{ rpm_folder }}/install.params"
  register: inst_params_status
  
- fail:
    msg: "Installation of {{ app_name }} is broken ! File install.params is missing in {{ install_prefix }}/{{ rpm_folder }}"
  when: not inst_params_status.stat.exists
