---
# This file handles installation with yum (to default folder /opt/talend)
#
- name: "Install {{ app_name }} with yum"
  when: rpm_is_installed.stdout == ''
  yum:
    name: "{{ rpm_name }}"
    state: present
  environment:
    TALEND_INSTALL_USER:    "{{ install_user }}"
    TALEND_INSTALL_GROUP:   "{{ install_group }}"
    TALEND_INSTALL_SYSTEMD: "{{ '1' if tac_install_systemd == 'yes' else '0' }}"
    TALEND_TOMCAT_HOME:     "{{ '' if tac_use_talend_tomcat == 'yes' else tac_tomcat_home }}"
    TALEND_TOMCAT_MODE:     "{{ '' if tac_use_talend_tomcat == 'yes' else tac_tomcat_mode }}"
    TALEND_TOMCAT_SETUP:    "{{ '' if tac_use_talend_tomcat == 'yes' else tac_tomcat_setup }}"
    TALEND_TOMCAT_PORT:     "{{ '' if tac_use_talend_tomcat == 'yes' else tac_tomcat_port }}"
