---
# Check params to be correct
- import_tasks: params_validation.yml

# Check tomcat-related things (when we use talend-tomcat rpm)
- import_tasks: check_tomcat.yml

# Check situation with current status (e.g. installed but into different path - that would be an error)
- import_tasks: check_status.yml

# We will include installation with yum or with rpm depending of prefix used
- include_tasks: install_yum.yml
  when: install_prefix == '/opt/talend'

- include_tasks: install_rpm.yml
  when: install_prefix != '/opt/talend'





#- name: Update TAC admin user
#  replace:
#    path: /opt/talend/tac/tomcat/webapps/org.talend.administrator/WEB-INF/classes/configuration.properties
#    regexp:  'install\.defaultaccount\.login=.*'
#    replace: 'install.defaultaccount.login={{ TAC_ADMIN_USER }}'

#- name: Update TAC admin password
#  replace:
#    path: /opt/talend/tac/tomcat/webapps/org.talend.administrator/WEB-INF/classes/configuration.properties
#    regexp:  'install\.defaultaccount\.password=.*'
#    replace: 'install.defaultaccount.password={{ TAC_ADMIN_PASS }}'
